//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mike.rc
//
#define ID_SCROLL_WINDOW                1000
#define IDS_GAME_PUBLIC                 1001
#define IDC_AD                          1001
#define IDS_GAME_PRIVATE                1002
#define IDS_DIFF_NORMAL                 1003
#define IDC_USERLIST                    1003
#define IDS_DIFF_NIGHTMARE              1004
#define IDS_DIFF_HELL                   1005
#define IDC_CHATWINDOW                  1005
#define IDS_PUBLIC_DESC                 1006
#define IDC_CHATEDIT                    1006
#define IDS_PRIVATE_DESC                1007
#define ID_CHATJOIN                     1007
#define ID_CHATCREATE                   1008
#define IDS_NAME_REQUIRED               1008
#define ID_SENDMSG                      1009
#define IDS_PASSWORD_REQUIRED           1009
#define IDC_EDIT_NAME                   1010
#define IDS_CHAT_HELP                   1010
#define IDC_EDIT_PASSWORD               1011
#define IDS_GAME_DESC_INCLNAME          1011
#define IDC_TYPE_PUBLIC                 1012
#define IDS_GAME_DESC                   1012
#define IDC_TYPE_PRIVATE                1013
#define IDS_NO_ALLOW_SPAWN              1013
#define IDC_DIF_NORMAL                  1014
#define IDS_DIFF_NORMAL_SHORT           1014
#define IDC_DIF_NIGHTMARE               1015
#define IDS_DIFF_NIGHTMARE_SHORT        1015
#define IDC_DIF_HELL                    1016
#define IDS_DIFF_HELL_SHORT             1016
#define IDS_NO_ALLOW_SPAWN_SHORT        1017
#define IDC_COMBO1                      1020
#define IDC_CHAT_CHANNEL                1020
#define IDC_EDIT1                       1022
#define IDS_NORMAL_DESC                 1023
#define IDS_NIGHTMARE_DESC              1024
#define IDS_HELL_DESC                   1025
#define IDS_OPEN_DESC                   1026
#define IDC_LIST1                       1027
#define IDS_RESTRICTED_DESC             1027
#define IDS_GAME_NAME_INVALID           1028
#define IDC_STATIC_DESC                 1029
#define IDC_STATIC_GAMETYPE_DESC        1029
#define IDS_NORMAL_DESC_XLONG           1029
#define IDC_TITLE                       1030
#define IDS_NIGHTMARE_DESC_XLONG        1030
#define IDC_GAMEDESCRIPTION             1031
#define IDS_HELL_DESC_XLONG             1031
#define IDC_RADIO_NORMAL                1032
#define IDS_LEVEL_AUTHORIZATION         1032
#define IDC_RADIO_NIGHTMARE             1033
#define IDS_GAMECREATOR_FMT             1033
#define IDS_GAMECREATOR                 1033
#define IDS_CREATOR                     1033
#define IDC_RADIO_HELL                  1034
#define IDS_AM                          1034
#define IDS_PM                          1035
#define IDS_CREATIONTIME_FMT            1036
#define IDS_TIME                        1037
#define IDS_CREATOR_FMT                 1038
#define IDS_GAMEALREADYEXISTS           1039
#define IDC_STATIC_DIFF_DESC            1040
#define IDS_CREATEGAMEERROR             1040
#define IDS_NIGHTMARE_MINREQ            1041
#define IDC_CHECK1                      1042
#define IDS_HELL_MINREQ                 1042
#define IDS_AUTH_STRTOOLONG             1043
#define IDS_AUTH_BADHERODESC            1044
#define IDS_AUTH_CHANNELRESTRICTED      1045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
