/****************************************************************************
*
*  bnetart.h
*
*  This file should be included by an application that wants to provide
*  battle.net-specific artwork in its art callback.
*
***/

enum _BATTLENET_ART {
	SNET_ART_BATTLE_BTNS = 0x80000000,
  SNET_ART_BATTLE_JOIN_BKG,
  SNET_ART_BATTLE_HELP_BKG,
	SNET_ART_BATTLE_LISTBOX,
	SNET_ART_BATTLE_GREENLAG,
	SNET_ART_BATTLE_YELLOWLAG,
	SNET_ART_BATTLE_REDLAG,
};

