/*
 *******************************************************************
 *** Important information for use with the                      ***
 *** PKWARE Data Compression Library (R) for Win32               ***
 *** Copyright 1994,1995 by PKWARE Inc. All Rights Reserved.     ***
 *** PKWARE Data Compression Library Reg. U.S. Pat. and Tm. Off. ***
 *******************************************************************
 */
//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DCL.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG1                     102
#define IDC_LIST1                       1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_EDIT3                       1005
#define IDC_EDIT4                       1006
#define IDC_EDIT5                       1007
#define IDC_EDIT6                       1008
#define IDC_EDIT7                       1009
#define IDC_BUTTON3                     1010
#define IDC_EDIT8                       1011
#define IDC_BUTTON4                     1012
#define IDC_EDIT9                       1013
#define COMP_DIALOG                     32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
