/*
 *******************************************************************
 *** Important information for use with the                      ***
 *** PKWARE Data Compression Library (R) for Win32               ***
 *** Copyright 1995 by PKWARE Inc. All Rights Reserved.          ***
 *** PKWARE Data Compression Library Reg. U.S. Pat. and Tm. Off. ***
 *******************************************************************
 */

#include <owl\owlpch.h>
#pragma hdrstop

#include "mm2mmapp.h"
#include "mm2mmedv.h"

#include <stdio.h>


//{{mem2memEditView Implementation}}


//////////////////////////////////////////////////////////
// mem2memEditView
// ==========
// Construction/Destruction handling.
mem2memEditView::mem2memEditView (TDocument& doc, TWindow* parent)
    : TEditView(doc, parent)
{
    // INSERT>> Your constructor code here.

}


mem2memEditView::~mem2memEditView ()
{
    // INSERT>> Your destructor code here.

}
