//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by standard.RC
//
#define IDS_PBADD                       1
#define IDS_PBEDIT                      2
#define IDC_CREATEGAME                  3
#define IDC_MODEMJOIN                   3
#define IDS_NODEVICES                   3
#define IDS_NOLOCATIONS                 4
#define IDS_DIALING                     5
#define IDS_RINGING                     6
#define IDS_CONNECTING                  7
#define IDS_PROCEEDING                  8
#define IDS_DIALTONE                    9
#define IDC_GAMEDESCRIPTION             103
#define IDC_PROGRAMDESCRIPTION          104
#define IDD_DIALOG1                     104
#define IDD_DIALOG2                     105
#define IDC_GAMELIST                    1001
#define IDC_EDIT1                       1002
#define IDC_LIST1                       1003
#define IDC_LOCATION                    1003
#define IDC_PHONEBOOK                   1003
#define IDC_EDIT2                       1004
#define IDC_LIST2                       1005
#define IDC_COMBO1                      1006
#define IDC_COUNTRYCODE                 1006
#define IDC_CALL                        1008
#define IDC_CANCEL                      1009
#define IDC_CHECK1                      1010
#define IDC_MODEMCREATE                 1011
#define IDC_DEVICELIST                  1013
#define IDC_CALLINGCARD                 1014
#define IDC_CHANGELOCATION              1015
#define IDC_CHANGEMODEM                 1016
#define IDC_PHONEBOOKADD                1017
#define IDC_PHONEBOOKREMOVE             1018
#define IDC_CURRENTMODEM                1019
#define IDC_CURRENTLOCATION             1020
#define IDC_PHONEBOOKEDIT               1021
#define IDC_PBNAME                      1021
#define IDC_AREACODE                    1022
#define IDC_PBNUMBER                    1023
#define IDC_PBOPERATION                 1025
#define IDC_LOCLIST                     1026
#define IDC_COUNTRY                     1026
#define IDC_CHANGECOUNTRY               1027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
