/*
 *******************************************************************
 *** Important information for use with the                      ***
 *** PKWARE Data Compression Library (R) for Win32               ***
 *** Copyright 1995 by PKWARE Inc. All Rights Reserved.          ***
 *** PKWARE Data Compression Library Reg. U.S. Pat. and Tm. Off. ***
 *******************************************************************
 */

#include <owl\owlpch.h>
#pragma hdrstop

#include "spanapp.h"
#include "spnedtvw.h"

#include <stdio.h>


//{{spanEditView Implementation}}


//////////////////////////////////////////////////////////
// spanEditView
// ==========
// Construction/Destruction handling.
spanEditView::spanEditView (TDocument& doc, TWindow* parent)
    : TEditView(doc, parent)
{
    // INSERT>> Your constructor code here.

}


spanEditView::~spanEditView ()
{
    // INSERT>> Your destructor code here.

}
