/*
 *******************************************************************
 *** Important information for use with the                      ***
 *** PKWARE Data Compression Library (R) for Win32               ***
 *** Copyright 1995 by PKWARE Inc. All Rights Reserved.          ***
 *** PKWARE Data Compression Library Reg. U.S. Pat. and Tm. Off. ***
 *******************************************************************
 */
//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SPAN.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDM_COMPRESS_FILES              32772
#define IDM_UNCOMPRESS_FILES            32773
#define IDM_CMP_BINARY                  32774
#define IDM_CMP_ASCII                   32775
#define IDM_DICT_SIZE_1024              32777
#define IDM_DICT_SIZE_2048              32778
#define IDM_DICT_SIZE_4096              32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
