#define  OEMRESOURCE
#define  STRICT
#define  _WIN32_WINNT  0x0400
#define  STORMSTATIC   // see prototypes for initialize and destroy functions
#include <windows.h>
#include <wincrypt.h>
#include <ddraw.h>
#include <dsound.h>
#include <smack.h>
#include <implode.h>
#include <assert.h>
#include <limits.h>
#include <math.h>
#include <process.h>
#include <stdio.h>
#include <string.h>
#include <tchar.h>
#include <time.h>
#include "storm.h"
#include "sintern.h"
#include "resource.h"
