//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by STORM.RC
//
#define  IDS_BASE                        0x5100
#define  IDS_ERROR                       0x5100
#define  IDS_HEADER                      0x5101
#define  IDS_PROGRAM                     0x5102
#define  IDS_FILELINE                    0x5103
#define  IDS_FUNCTION                    0x5104
#define  IDS_OBJECT                      0x5105
#define  IDS_HANDLE                      0x5106
#define  IDS_EXPRESSION                  0x5107
#define  IDS_DESCRIPTION                 0x5108
#define  IDS_TERMINATE                   0x5109
#define  IDS_RECOVERABLE                 0x510A
#define  IDS_FILE                        0x510B
#define  IDS_BADARGUMENT                 0x5201
#define  IDS_NOTENOUGHARGUMENTS          0x5202
#define  IDS_OPENFAILED                  0x5203

#define  IDC_CREATEGAME                  0x5180
#define  IDC_PROVIDERLIST                0x5181
#define  IDC_MAXPLAYERS                  0x5182
#define  IDC_REQUIREMENTS                0x5183
#define  IDC_PROGRAMDESCRIPTION          0x5184

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
