//**************************************
// regconst.h
// written 9.17.94
// written by Patrick Wyatt
//**************************************


//**************************************
// registration blocks
//**************************************
	// length of registration block embedded in program
	#define REG_LEN			128

	// length of table of registration blocks embedded in program
	#define TBL_LEN			128

	// offset to registration block
	typedef ULONG 			REG_OFF;
	#define MAX_REGS		10

