//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Diablo.rc
//
#define IDI_ICON1                       101
#define IDD_DDRAW_ERR                   104
#define IDD_MEM_ERR                     105
#define IDD_FILE_ERR                    106
#define IDD_DDRAW_DLL_ERR               107
#define IDD_DSOUND_DLL_ERR              108
#define IDD_CHIP_ERR                    109
#define IDD_DISKFREE_ERR                110
#define IDI_ICON2                       110
#define IDD_DDRAW_PAL_ERR               111
#define IDD_CDROM_ERR                   112
#define IDC_ERROR_TAG                   1000
#define IDESCAPE                        1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
